### ISSUE TITLE
Settaggio in config.js

### ISSUE THREAD

**Issue by sibberio** [SuperCaliMan/MMM-Trenitalia#1]
Ciao, ho installato il modulo ma non riesco a capire come mettere la stazione di partenza e di arrivo in config.js

Grazie!

**Comment by SuperCaliMan** [comment]
Ciao purtroppo non ho ancora implementato la possibilità di impostare mediante il file config.js la stazione di partenza e arrivo. Per farlo devi inserire i codici delle stazioni nel file TrainData.js 
`'http://www.viaggiatreno.it/viaggiatrenonew/resteasy/viaggiatreno/soluzioniViaggioNew/STAZIONE_ PARTENZA/STAZIONE_ARRIVO/'+date;`

**Comment by sibberio** [comment]
Grazie della dritta, sono riuscito a farlo partire!
Purtroppo nel docker di MagicMirror manca il modulo symc-request e quindi oltre ad avere il problema di capire come mettere le stazioni mi crashava tutto quanto. Ora ho risolto!

**Comment by SuperCaliMan** [comment]
Il modulo sync-request prevede di fare delle chiamate SINCRONE alla rest api di trenitalia, si consiglia di non utilizzarlo in produzione.

**Comment by sibberio** [comment]
Senza sync-request il docker di Magicmirror va in palla!

**Comment by SuperCaliMan** [comment]
Sync-request è necessaria per fare le chiamate alle api di trenitalia, installala con npm nel tuo server node e poi avvi magic mirror
